cluster.kind=CENTER
cluster.region=r1
cluster.node=center-1
cluster.host=127.0.0.1
cluster.port=9000
cluster.center.host=127.0.0.1
cluster.center.port=9000
cluster.ops.host=127.0.0.1
cluster.ops.port=19000
cluster.actor.workers=2
cluster.registry.lease.scan.interval.millis=1000
cluster.event.history.default.limit=10000
cluster.event.history.topic.profile.changed.limit=20000
