cluster.deployment.services=center,game,chat,scene-small,scene-large,proxy,region

cluster.deployment.service.center.kind=CENTER
cluster.deployment.service.center.config=cluster/center.properties
cluster.deployment.service.center.main=com.commonbattle.cluster.boot.CenterServerMain
cluster.deployment.service.center.watches=CENTER,GAME,CHAT,SCENE,PROXY,REGION
cluster.deployment.service.center.startsAfter=

cluster.deployment.service.game.kind=GAME
cluster.deployment.service.game.config=cluster/game.properties
cluster.deployment.service.game.main=com.commonbattle.cluster.boot.GameServerMain
cluster.deployment.service.game.watches=CHAT,SCENE,PROXY,REGION
cluster.deployment.service.game.startsAfter=center,proxy

cluster.deployment.service.chat.kind=CHAT
cluster.deployment.service.chat.config=cluster/chat.properties
cluster.deployment.service.chat.main=com.commonbattle.cluster.boot.ChatServerMain
cluster.deployment.service.chat.watches=GAME,SCENE,PROXY,REGION
cluster.deployment.service.chat.startsAfter=center,proxy

cluster.deployment.service.scene-small.kind=SCENE
cluster.deployment.service.scene-small.config=cluster/scene-small.properties
cluster.deployment.service.scene-small.main=com.commonbattle.cluster.boot.SceneServerMain
cluster.deployment.service.scene-small.watches=GAME,CHAT,PROXY,REGION
cluster.deployment.service.scene-small.startsAfter=center,proxy

cluster.deployment.service.scene-large.kind=SCENE
cluster.deployment.service.scene-large.config=cluster/scene-large.properties
cluster.deployment.service.scene-large.main=com.commonbattle.cluster.boot.SceneServerMain
cluster.deployment.service.scene-large.watches=GAME,CHAT,PROXY,REGION
cluster.deployment.service.scene-large.startsAfter=center,proxy

cluster.deployment.service.proxy.kind=PROXY
cluster.deployment.service.proxy.config=cluster/proxy.properties
cluster.deployment.service.proxy.main=com.commonbattle.cluster.boot.ProxyServerMain
cluster.deployment.service.proxy.watches=CENTER,GAME,CHAT,SCENE,REGION
cluster.deployment.service.proxy.startsAfter=center

cluster.deployment.service.region.kind=REGION
cluster.deployment.service.region.config=cluster/region.properties
cluster.deployment.service.region.main=com.commonbattle.cluster.boot.RegionServerMain
cluster.deployment.service.region.watches=GAME,CHAT,SCENE,PROXY
cluster.deployment.service.region.startsAfter=center,proxy
