cluster.kind=PROXY
cluster.region=r1
cluster.node=proxy-1
cluster.host=127.0.0.1
cluster.port=9004
cluster.center.host=127.0.0.1
cluster.center.port=9000
cluster.ops.host=127.0.0.1
cluster.ops.port=19004
cluster.actor.workers=2
cluster.registry.lease.ttl.millis=15000
cluster.registry.heartbeat.interval.millis=5000
