cluster.kind=SCENE
cluster.region=r1
cluster.node=scene-small-1
cluster.host=127.0.0.1
cluster.port=9002
cluster.center.host=127.0.0.1
cluster.center.port=9000
cluster.actor.workers=4
scene.mode=MULTI_SMALL_SCENE
scene.capacity=200
