package com.commonbattle.game.session;

/**
 * 玩家客户端网关错误码。
 */
public enum PlayerClientErrorCode {
    OK,
    AUTH_REJECTED,
    DUPLICATE_LOGIN,
    LOGIN_FAILED,
    NOT_LOGGED_IN,
    SESSION_EXPIRED,
    COMMAND_RATE_LIMITED,
    COMMAND_BACKPRESSURED,
    COMMAND_REMOTE_TIMEOUT,
    COMMAND_REMOTE_UNAVAILABLE,
    COMMAND_REMOTE_REJECTED,
    COMMAND_REMOTE_DRAINING,
    COMMAND_REMOTE_CIRCUIT_OPEN,
    COMMAND_INGRESS_FAILED,
    HEARTBEAT_RATE_LIMITED,
    INVALID_PAYLOAD,
    INVALID_FRAME,
    IDLE_TIMEOUT,
    SLOW_CLIENT
}
